### ISSUE TITLE
What is the debug mode in safe_eval.py and model.py's class GPT?

### ISSUE THREAD

**Issue by xndong** [uw-nsl/ArtPrompt#1]
1. A EVAL_DEBUG = False is set in safe_eval.py, and the variable is passed into class GPT in model.py.
The question is why do you set such a variable? What is its functionality?

2. Why do you catch openai.BadRequestError in model.py and check the repetitive pattern in error? It make the code hard to understand?

**Comment by Django-Jiang** [comment]
These are designed to resolve the special issue we encountered when evaluating.
- EVAL_DEBUG is to help not using retry mechnisim, that is primarily designed for API calling stability. As its name, help debug if any issue with the API calling. 
- openai.BadRequestError is a rare case, which we did not know the root cause for the corresponding case, and to a fair setup, we set it as a fail attack attempt.

All these designs are primarily designed for running stable inference pipelines, and this can be replaced with any other inference library with similar functionality.
