### ISSUE TITLE
Three problems about the repo or experiment.

### ISSUE THREAD

**Issue by xndong** [uw-nsl/ArtPrompt#2]
Another three problems are as follows:

First, there is a bug in base_prompt.py. In the `class vitc_vertical(BasePrompt):` the `gen` method infers a non-exist List  named `alphabet_ascii`. So I was wondering, did you delete some part of code in your public version?

Second, what the experiment setting or running command to achieve the evaluation results in your paper? The setting comes from v/h with fonts, but the paper did not explain the details? h with alphabet, h with letters, h with gen...？Or v with cards, v with puzzle...？ 

Third， would you like to release you experimental json file, so that it will be helpful to re-evaluate without inferencing.

**Comment by Django-Jiang** [comment]
1. Thanks for pointing this out. This is a naming issue when we clean the public release codebase, and I have corrected it now.
2. We have font name sets used for evaluation stated in our paper, please refer to appendix A.3 for details. Specially, top-1 setup in table 3 use `h-gen`, and Ensemble use `h-gen/alphabet/keyboard/cards/letters/puzzle`,  please run each individual font results and use the `ensemble_eval.ipynb` notebook to get ensemble evaluation results. The top-1 setup is subject to change given the different setups of victim models, we determined the top-1 font based on the average performance on our victim model sets.
3. We did not release the attack prompt artifact since Our method can be produced at very low cost. Regarding the response artifact, we did not plan to release it due to the ethical considerations.
