### ISSUE TITLE
Question on response of some LLM when being attacked by ArtPrompt

### ISSUE THREAD

**Issue by Fancyssc** [uw-nsl/ArtPrompt#4]

**Comment by Fancyssc** [comment]
Hello, Dear author:
When During the reproduction process, we found that in some scenarios involving artprompt attacks, we replaced sensitive words with a mask using GPT-3.5 and then converted the mask into ASC Art format. However, this type of attack sometimes caused models to output garbled text resembling ASC Art instead of producing normal results. How can such outputs be evaluated, or have you considered ways to constrain the outputs of the tested models?

**Comment by Django-Jiang** [comment]
Hi, I am not sure the exact pipeline you worked with GPT-3.5 to replace sensitive words, we had a primary trial on this idea to use GPT-3.5 for selectively replacing sensitive words, but GPT-3.5 shows poor performance in the sense of finding sensitive words and replacing the words. I would suggest you to try also GPT-4o-mini at least, or GPT-4o. Also, in our experiment, we found the success attack case is not always the instruction that replacing the most sensitive words from a human perspective, so I would suggest that you can optimize your prompt, instead of 'replacing sensitive words', try 'replacing word that may make the model not refuse the instruction' or some other prompt.

I am interested in your experiments with this new design
